name: tweet_up
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.2
  firebase_core: ^2.10.0
  google_sign_in: ^6.2.1
  provider: ^6.0.4
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.7
  mailto: ^2.0.0
  flutter_speed_dial: ^7.0.0
  shared_preferences: ^2.0.15
  fluttericon: ^2.0.0
  firebase_storage: ^11.1.1
  file_picker: ^6.1.1
  firebase_messaging: ^14.2.6
  flutter_local_notifications: ^16.3.2
  http: ^1.0.0
  image_picker: ^1.0.7
  percent_indicator: ^4.2.2
  another_flushbar: 1.12.30
  flutter_bloc: ^8.1.2
  path_provider: ^2.0.12
  equatable: ^2.0.5
  image_gallery_saver: ^2.0.3
  intl: ^0.19.0
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter_native_splash:
  color: "#ffffff"
  android_12:
  android: true
  ios: true
  image: assets/images/app_icon.png

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - assets/images/screenshots/
    - assets/sounds/

  fonts:
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
          style: italic
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
          weight: 500
        - asset: fonts/Poppins-BlackItalic.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Medium.ttf


